// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api_careluna.Data;

#nullable disable

namespace api_careluna.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251120021949_NombreColumns")]
    partial class NombreColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api_careluna.Data.PedidosModel", b =>
                {
                    b.Property<int>("ped_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ped_Id"));

                    b.Property<int>("Clientecli_Id")
                        .HasColumnType("integer");

                    b.Property<int>("cli_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ped_Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ped_Total")
                        .HasColumnType("numeric");

                    b.HasKey("ped_Id");

                    b.HasIndex("Clientecli_Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("api_careluna.Models.ClientesModel", b =>
                {
                    b.Property<int>("cli_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cli_Id"));

                    b.Property<string>("cli_Celular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cli_Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cli_Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cli_RazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("cli_Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("api_careluna.Models.PedidoProductoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteProductopc_id")
                        .HasColumnType("integer");

                    b.Property<int>("Pedidoped_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUsado")
                        .HasColumnType("numeric");

                    b.Property<int>("pc_id")
                        .HasColumnType("integer");

                    b.Property<int>("ped_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteProductopc_id");

                    b.HasIndex("Pedidoped_Id");

                    b.ToTable("PedidoProducto");
                });

            modelBuilder.Entity("api_careluna.Models.ProductoClienteModel", b =>
                {
                    b.Property<int>("pc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("pc_id"));

                    b.Property<int>("Clientecli_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Productospro_Id")
                        .HasColumnType("integer");

                    b.Property<int>("cli_id")
                        .HasColumnType("integer");

                    b.Property<int>("pc_Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("pc_Precio")
                        .HasColumnType("numeric");

                    b.Property<int>("pro_id")
                        .HasColumnType("integer");

                    b.HasKey("pc_id");

                    b.HasIndex("Clientecli_Id");

                    b.HasIndex("Productospro_Id");

                    b.ToTable("ProductoCliente");
                });

            modelBuilder.Entity("api_careluna.Models.ProductosModel", b =>
                {
                    b.Property<int>("pro_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("pro_Id"));

                    b.Property<string>("pro_Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("pro_Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("pro_Precio")
                        .HasColumnType("numeric");

                    b.HasKey("pro_Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("api_careluna.Data.PedidosModel", b =>
                {
                    b.HasOne("api_careluna.Models.ClientesModel", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("Clientecli_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("api_careluna.Models.PedidoProductoModel", b =>
                {
                    b.HasOne("api_careluna.Models.ProductoClienteModel", "ClienteProducto")
                        .WithMany()
                        .HasForeignKey("ClienteProductopc_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_careluna.Data.PedidosModel", "Pedido")
                        .WithMany("Productos")
                        .HasForeignKey("Pedidoped_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteProducto");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("api_careluna.Models.ProductoClienteModel", b =>
                {
                    b.HasOne("api_careluna.Models.ClientesModel", "Cliente")
                        .WithMany("ProductosPersonalizados")
                        .HasForeignKey("Clientecli_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_careluna.Models.ProductosModel", "Productos")
                        .WithMany("productoClientes")
                        .HasForeignKey("Productospro_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("api_careluna.Data.PedidosModel", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("api_careluna.Models.ClientesModel", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("ProductosPersonalizados");
                });

            modelBuilder.Entity("api_careluna.Models.ProductosModel", b =>
                {
                    b.Navigation("productoClientes");
                });
#pragma warning restore 612, 618
        }
    }
}
